import { constants } from "node:fs"
import { access, chmod, mkdir, writeFile } from "node:fs/promises"
import { join, resolve } from "node:path"

const HOOK_SCRIPT = `#!/usr/bin/env bash
#
# Fiction Map pre-commit hook
# Auto-generated by \`fiction-map hooks install\`

# Check if any graph primitives are staged
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\\.(node|edge|condition|effect|graph)\\.ts$' || true)

if [ -n "$STAGED_FILES" ]; then
  echo "🔍 Fiction Map: Graph primitives modified, verifying..."
  
  # Find runner
  if [ -f "bun.lockb" ] || [ -f "bun.lock" ]; then
    RUNNER="bun x"
  elif [ -f "pnpm-lock.yaml" ]; then
    RUNNER="pnpm dlx"
  elif [ -f "yarn.lock" ]; then
    RUNNER="yarn dlx"
  else
    RUNNER="npx"
  fi

  $RUNNER fiction-map generate --check
  GEN_STATUS=$?

  if [ $GEN_STATUS -ne 0 ]; then
    echo "❌ Fiction Map: Generated artifacts are out of date. Run 'fiction-map generate' and stage the changes."
    exit 1
  fi

  $RUNNER fiction-map validate
  VAL_STATUS=$?

  if [ $VAL_STATUS -ne 0 ]; then
    echo "❌ Fiction Map: Validation failed."
    exit 1
  fi
  
  echo "✅ Fiction Map: All checks passed."
fi

exit 0
`

export async function installHooks(rootDir: string = process.cwd()): Promise<void> {
  const gitDir = join(resolve(rootDir), ".git")

  try {
    await access(gitDir, constants.F_OK)
  } catch {
    console.error(`❌ No .git directory found at ${gitDir}. Are you in the repository root?`)
    process.exit(1)
  }

  const hooksDir = join(gitDir, "hooks")
  const preCommitPath = join(hooksDir, "pre-commit")

  try {
    await mkdir(hooksDir, { recursive: true })

    let existingHook = ""
    try {
      const { readFile } = await import("node:fs/promises")
      existingHook = await readFile(preCommitPath, "utf8")
    } catch {
      // File doesn't exist, which is fine
    }

    if (existingHook.includes("Fiction Map pre-commit hook")) {
      console.log("✅ Fiction Map pre-commit hook is already installed.")
      return
    }

    if (existingHook && existingHook.trim() !== "") {
      // Append to existing hook without the shebang
      const scriptBody = HOOK_SCRIPT.replace(/^#![^\n]+\n/, "")
      const appendContent = `\n\n${scriptBody}`
      await writeFile(preCommitPath, existingHook + appendContent)
      console.log("✅ Appended Fiction Map to existing pre-commit hook.")
    } else {
      // Create new hook
      await writeFile(preCommitPath, HOOK_SCRIPT)
      console.log("✅ Installed Fiction Map pre-commit hook.")
    }

    await chmod(preCommitPath, "755")
  } catch (error) {
    console.error("❌ Failed to install git hook:")
    console.error(error)
    process.exit(1)
  }
}
