import fs from "node:fs"
import path from "node:path"

const rootDir = path.resolve(__dirname, "..")
const tsPath = path.join(rootDir, "src/generated/protocol.ts")
const goPath = path.join(rootDir, "go/generated/protocol.go")

const tsContent = `// Code generated by fiction-map. DO NOT EDIT.
export type Frame = any
export type Intent = any
`

const goContent = `// Code generated by fiction-map. DO NOT EDIT.
package generated
`

function run() {
  const checkMode = process.argv.includes("--check")

  if (checkMode) {
    const tsCurrent = fs.existsSync(tsPath) ? fs.readFileSync(tsPath, "utf-8") : ""
    const goCurrent = fs.existsSync(goPath) ? fs.readFileSync(goPath, "utf-8") : ""

    if (tsCurrent !== tsContent || goCurrent !== goContent) {
      console.error("❌ Error: Generated protocol bindings are out of sync with the schema.")
      console.error("👉 Please run 'bun run generate' inside packages/protocol to regenerate them.")
      process.exit(1)
    }

    console.log("✅ Generated protocol bindings are up to date.")
    process.exit(0)
  }

  // Ensure directories exist
  fs.mkdirSync(path.dirname(tsPath), { recursive: true })
  fs.mkdirSync(path.dirname(goPath), { recursive: true })

  fs.writeFileSync(tsPath, tsContent, "utf-8")
  fs.writeFileSync(goPath, goContent, "utf-8")

  console.log("✨ Successfully generated protocol bindings.")
}

run()
