import fs from "node:fs"
import path from "node:path"

const rootDir = path.resolve(__dirname, "..")
const tsPath = path.join(rootDir, "src/generated/protocol.ts")
const goPath = path.join(rootDir, "go/generated/protocol.go")

const tsContent = `// Code generated by fiction-map. DO NOT EDIT.

export interface FrameNodeBlock {
  id: string
  type: "paragraph" | "header" | "image"
  text?: string
  url?: string
  caption?: string
  metadata?: Record<string, any>
}

export interface FrameNode {
  id: string
  type: string
  blocks?: FrameNodeBlock[]
}

export interface FrameChoice {
  id: string
  label: string
}

export interface FrameInventoryItem {
  id: string
  label: string
}

export interface FramePacing {
  pacingIndex: number
  isComplete: boolean
}

export interface Frame {
  currentNode: FrameNode
  choices: FrameChoice[]
  resources: Record<string, number>
  inventory: FrameInventoryItem[]
  flags: Record<string, boolean | string | number>
  warnings: string[]
  pacing: FramePacing
  serializedState: string
}

export interface Intent {
  type: "selectChoice" | "skipPacing" | "save" | "load" | "quit"
  choiceId?: string
  saveSlot?: string
  serializedState?: string
}
`

const goContent = `// Code generated by fiction-map. DO NOT EDIT.
package generated

type FrameNodeBlock struct {
	ID       string                 \`json:"id"\`
	Type     string                 \`json:"type"\`
	Text     string                 \`json:"text,omitempty"\`
	URL      string                 \`json:"url,omitempty"\`
	Caption  string                 \`json:"caption,omitempty"\`
	Metadata map[string]interface{} \`json:"metadata,omitempty"\`
}

type FrameNode struct {
	ID     string           \`json:"id"\`
	Type   string           \`json:"type"\`
	Blocks []FrameNodeBlock \`json:"blocks,omitempty"\`
}

type FrameChoice struct {
	ID    string \`json:"id"\`
	Label string \`json:"label"\`
}

type FrameInventoryItem struct {
	ID    string \`json:"id"\`
	Label string \`json:"label"\`
}

type FramePacing struct {
	PacingIndex int  \`json:"pacingIndex"\`
	IsComplete  bool \`json:"isComplete"\`
}

type Frame struct {
	CurrentNode     FrameNode              \`json:"currentNode"\`
	Choices         []FrameChoice          \`json:"choices"\`
	Resources       map[string]float64     \`json:"resources"\`
	Inventory       []FrameInventoryItem   \`json:"inventory"\`
	Flags           map[string]interface{} \`json:"flags"\`
	Warnings        []string               \`json:"warnings"\`
	Pacing          FramePacing            \`json:"pacing"\`
	SerializedState string                 \`json:"serializedState"\`
}

type Intent struct {
	Type            string \`json:"type"\`
	ChoiceID        string \`json:"choiceId,omitempty"\`
	SaveSlot        string \`json:"saveSlot,omitempty"\`
	SerializedState string \`json:"serializedState,omitempty"\`
}
`

function run() {
  const checkMode = process.argv.includes("--check")

  if (checkMode) {
    const tsCurrent = fs.existsSync(tsPath) ? fs.readFileSync(tsPath, "utf-8") : ""
    const goCurrent = fs.existsSync(goPath) ? fs.readFileSync(goPath, "utf-8") : ""

    if (tsCurrent !== tsContent || goCurrent !== goContent) {
      console.error("❌ Error: Generated protocol bindings are out of sync with the schema.")
      console.error("👉 Please run 'bun run generate' inside packages/protocol to regenerate them.")
      process.exit(1)
    }

    console.log("✅ Generated protocol bindings are up to date.")
    process.exit(0)
  }

  // Ensure directories exist
  fs.mkdirSync(path.dirname(tsPath), { recursive: true })
  fs.mkdirSync(path.dirname(goPath), { recursive: true })

  fs.writeFileSync(tsPath, tsContent, "utf-8")
  fs.writeFileSync(goPath, goContent, "utf-8")

  console.log("✨ Successfully generated protocol bindings.")
}

run()
