#!/usr/bin/env bun
import { readdir, readFile, writeFile } from "fs/promises";
import { join, basename } from "path";

interface NodeTypeDefinition {
  id: string;
  name: string;
  description?: string;
  aiRule?: string;
  properties: Record<string, unknown>;
}

interface EdgeTypeDefinition {
  id: string;
  name: string;
  description?: string;
  sourceTypes: string[];
  targetTypes: string[];
  properties: Record<string, unknown>;
}

function camelCase(str: string): string {
  return str
    .replace(/[-_]([a-z])/g, (_, c) => c.toUpperCase())
    .replace(/\.node-type\.ts$|\.edge-type\.ts$/, "");
}

async function discoverNodeTypes(dir: string): Promise<NodeTypeDefinition[]> {
  const types: NodeTypeDefinition[] = [];
  try {
    const files = await readdir(dir);
    for (const file of files) {
      if (!file.endsWith(".node-type.ts")) continue;
      
      const content = await readFile(join(dir, file), "utf-8");
      const id = camelCase(file);
      const name = id + "NodeType";
      
      const descriptionMatch = content.match(/@description\s+(.+)/);
      const aiRuleMatch = content.match(/@ai-rule\s+(.+)/);
      
      types.push({
        id,
        name,
        description: descriptionMatch?.[1],
        aiRule: aiRuleMatch?.[1],
        properties: {},
      });
    }
  } catch {}
  return types;
}

async function discoverEdgeTypes(dir: string): Promise<EdgeTypeDefinition[]> {
  const types: EdgeTypeDefinition[] = [];
  try {
    const files = await readdir(dir);
    for (const file of files) {
      if (!file.endsWith(".edge-type.ts")) continue;
      
      const content = await readFile(join(dir, file), "utf-8");
      const id = camelCase(file);
      const name = id + "EdgeType";
      
      const descriptionMatch = content.match(/@description\s+(.+)/);
      const aiRuleMatch = content.match(/@ai-rule\s+(.+)/);
      
      types.push({
        id,
        name,
        description: descriptionMatch?.[1],
        aiRule: aiRuleMatch?.[1],
        sourceTypes: [],
        targetTypes: [],
        properties: {},
      });
    }
  } catch {}
  return types;
}

async function generateRegistry(pkgPath: string, pkgName: string) {
  const nodeTypes = await discoverNodeTypes(join(pkgPath, "src/node-types"));
  const edgeTypes = await discoverEdgeTypes(join(pkgPath, "src/edge-types"));
  
  const exports: string[] = [];
  
  if (nodeTypes.length > 0) {
    exports.push("// Node Types");
    for (const nt of nodeTypes) {
      exports.push(`export { ${nt.name} } from "./node-types/${nt.id}.node-type.js";`);
    }
    exports.push("");
  }
  
  if (edgeTypes.length > 0) {
    exports.push("// Edge Types");
    for (const et of edgeTypes) {
      exports.push(`export { ${et.name} } from "./edge-types/${et.id}.edge-type.js";`);
    }
    exports.push("");
  }
  
  const registryContent = `// @generated by scripts/generate-registry.ts
// DO NOT EDIT - changes will be overwritten

${exports.join("\n")}

export const ${pkgName.replace(/[^a-zA-Z0-9]/g, "")}Registry = {
  nodeTypes: [${nodeTypes.map(n => n.name).join(", ")}],
  edgeTypes: [${edgeTypes.map(e => e.name).join(", ")}],
};
`;
  
  await writeFile(join(pkgPath, "src/registry.generated.ts"), registryContent);
  console.log(`Generated registry for ${pkgName}: ${nodeTypes.length} nodes, ${edgeTypes.length} edges`);
}

async function generateSemanticsDoc(pkgPath: string, pkgName: string) {
  const nodeTypes = await discoverNodeTypes(join(pkgPath, "src/node-types"));
  const edgeTypes = await discoverEdgeTypes(join(pkgPath, "src/edge-types"));
  
  const lines: string[] = [
    `# ${pkgName} Semantics`,
    "",
    "> @generated by scripts/generate-registry.ts - DO NOT EDIT",
    "",
    "## Node Types",
    "",
  ];
  
  for (const nt of nodeTypes) {
    lines.push(`<node_type id="${nt.id}">`);
    if (nt.description) lines.push(`  <description>${nt.description}</description>`);
    if (nt.aiRule) lines.push(`  <ai_rule>${nt.aiRule}</ai_rule>`);
    lines.push(`</node_type>`);
    lines.push("");
  }
  
  lines.push("## Edge Types", "");
  for (const et of edgeTypes) {
    lines.push(`<edge_type id="${et.id}">`);
    if (et.description) lines.push(`  <description>${et.description}</description>`);
    if (et.aiRule) lines.push(`  <ai_rule>${et.aiRule}</ai_rule>`);
    lines.push(`</edge_type>`);
    lines.push("");
  }
  
  await writeFile(join(pkgPath, "SEMANTICS.md"), lines.join("\n"));
}

const packages = [
  { path: "packages/story-runtime", name: "@your-org/story-runtime" },
  { path: "packages/story-graph-flow", name: "@your-org/story-graph-flow" },
];

for (const pkg of packages) {
  await generateRegistry(pkg.path, pkg.name);
  await generateSemanticsDoc(pkg.path, pkg.name);
}

console.log("\nRegistries generated successfully.");
