import { defineGraph } from "@fiction-map/core"
import { registry } from "../project"

export const story = defineGraph(registry, {
  id: "library-mystery",
  nodes: [
    {
      id: "entrance",
      type: "scene",
      blocks: [
        {
          id: "entrance-desc",
          type: "paragraph",
          text: "You stand at the entrance to the old library.",
        },
      ],
    },
    {
      id: "main-hall",
      type: "scene",
      blocks: [
        {
          id: "hall-desc",
          type: "paragraph",
          text: "Dust motes float in shafts of grey light. A lantern sits on a table.",
        },
        {
          id: "hall-passage",
          type: "paragraph",
          text: "In the center of the hall, a yawning dark chasm drops into the earth.",
        },
        {
          id: "hall-archives",
          type: "paragraph",
          text: "To your left, the heavy iron-reinforced doors of the archives loom.",
        },
      ],
    },
    {
      id: "archives",
      type: "scene",
      blocks: [
        {
          id: "archives-desc",
          type: "paragraph",
          text: "Towering shelves hold forgotten lore. Magical tomes rest on reading pedestals, and a spectral librarian floats nearby.",
          metadata: { delayAfterMs: 400 },
        },
        {
          id: "archives-heal-tome",
          type: "paragraph",
          text: "On a brass stand rests the glowing 'Tome of Heal Spell'.",
        },
        {
          id: "archives-light-tome",
          type: "paragraph",
          text: "On a nearby desk rests the 'Tome of Mage Light Spell'.",
        },
        {
          id: "archives-librarian",
          type: "paragraph",
          text: "The spectral librarian gazes at you, offering lockpicks for trade.",
        },
      ],
    },
    {
      id: "dark-chapter",
      type: "scene",
      blocks: [
        {
          id: "chapter-desc",
          type: "paragraph",
          text: "A narrow passage drops into darkness. You hear the crackle of ancient magic.",
        },
      ],
    },
    {
      id: "chamber-of-runes",
      type: "scene",
      blocks: [
        {
          id: "runes-desc",
          type: "paragraph",
          text: "Glowing glyphs pulsate on the walls. A central stone pedestal holds a shining key.",
        },
      ],
    },
    {
      id: "collapsed-bridge",
      type: "scene",
      blocks: [
        {
          id: "bridge-desc",
          type: "paragraph",
          text: "A stone bridge has collapsed over a bottomless chasm. Dust and rubble are everywhere.",
        },
      ],
    },
    {
      id: "forgotten-crypt",
      type: "scene",
      blocks: [
        {
          id: "crypt-desc",
          type: "paragraph",
          text: "An ancient crypt, smelling of age. A massive iron casket lies in the center.",
        },
      ],
    },
    {
      id: "victory",
      type: "scene",
      blocks: [
        {
          id: "victory-desc",
          type: "paragraph",
          text: "You successfully unlocked the iron casket, revealing the legendary treasure of the Library!",
        },
      ],
    },
    {
      id: "death",
      type: "scene",
      blocks: [
        {
          id: "death-desc",
          type: "paragraph",
          text: "The dark forces of the passage overwhelm you. Your journey ends here.",
        },
      ],
    },
  ],
  edges: [
    {
      id: "enter-hall",
      type: "choice",
      source: "entrance",
      target: "main-hall",
      text: "Step inside",
      effects: [
        { type: "grantEntity", entityId: "lantern" },
        { type: "addResource", key: "health", amount: 100 },
        { type: "addResource", key: "mana", amount: 50 },
        { type: "addResource", key: "gold", amount: 30 },
        { type: "addResource", key: "turns", amount: 0 },
      ],
      anchorBlockId: "entrance-desc",
    },
    {
      id: "explore-archives",
      type: "choice",
      source: "main-hall",
      target: "archives",
      text: "Explore the Dusty Archives",
      conditions: [{ type: "notVisited", nodeId: "archives" }],
      anchorBlockId: "hall-archives",
    },
    {
      id: "study-heal",
      type: "choice",
      source: "archives",
      target: "archives",
      text: "Study the Tome of Heal Spell",
      conditions: [{ type: "notVisited", nodeId: "study-heal" }],
      effects: [
        { type: "grantEntity", entityId: "heal-spell" },
        { type: "markVisited", nodeId: "study-heal" },
      ],
      anchorBlockId: "archives-heal-tome",
    },
    {
      id: "study-mage-light",
      type: "choice",
      source: "archives",
      target: "archives",
      text: "Study the Tome of Mage Light Spell",
      conditions: [{ type: "notVisited", nodeId: "study-mage-light" }],
      effects: [
        { type: "grantEntity", entityId: "mage-light" },
        { type: "markVisited", nodeId: "study-mage-light" },
      ],
      anchorBlockId: "archives-light-tome",
    },
    {
      id: "buy-lockpick",
      type: "choice",
      source: "archives",
      target: "archives",
      text: "Buy a lockpick from the spectral librarian (-15 gold)",
      conditions: [
        { type: "notVisited", nodeId: "buy-lockpick" },
        { type: "resourceAtLeast", key: "gold", value: 15 },
      ],
      effects: [
        { type: "spendResource", key: "gold", amount: 15, clampToZero: true },
        { type: "grantEntity", entityId: "lockpick" },
        { type: "markVisited", nodeId: "buy-lockpick" },
      ],
      anchorBlockId: "archives-librarian",
    },
    {
      id: "return-from-archives",
      type: "choice",
      source: "archives",
      target: "main-hall",
      text: "Return to the Main Hall",
      anchorBlockId: "archives-desc",
    },
    {
      id: "descend",
      type: "choice",
      source: "main-hall",
      target: "dark-chapter",
      text: "Descend into the passage using the lantern",
      conditions: [{ type: "hasEntity", entityId: "lantern" }],
      anchorBlockId: "hall-passage",
    },
    {
      id: "examine-glyphs",
      type: "choice",
      source: "dark-chapter",
      target: "chamber-of-runes",
      text: "Examine the glowing glyphs",
      anchorBlockId: "chapter-desc",
    },
    {
      id: "cast-mage-light",
      type: "choice",
      source: "dark-chapter",
      target: "chamber-of-runes",
      text: "Cast Mage Light Spell and proceed safely (-15 MP)",
      conditions: [
        { type: "hasEntity", entityId: "mage-light" },
        { type: "resourceAtLeast", key: "mana", value: 15 },
      ],
      effects: [{ type: "spendResource", key: "mana", amount: 15, clampToZero: true }],
      anchorBlockId: "chapter-desc",
    },
    {
      id: "cross-bridge",
      type: "choice",
      source: "dark-chapter",
      target: "collapsed-bridge",
      text: "Cross the crumbling bridge",
      effects: [{ type: "spendResource", key: "health", amount: 40, clampToZero: true }],
      anchorBlockId: "chapter-desc",
    },
    {
      id: "translate-runes",
      type: "choice",
      source: "chamber-of-runes",
      target: "forgotten-crypt",
      text: "Translate the runes using the lantern",
      conditions: [{ type: "hasEntity", entityId: "lantern" }],
      effects: [{ type: "grantEntity", entityId: "key" }],
      anchorBlockId: "runes-desc",
    },
    {
      id: "touch-pedestal",
      type: "choice",
      source: "chamber-of-runes",
      target: "chamber-of-runes",
      text: "Touch the central pedestal",
      effects: [{ type: "spendResource", key: "health", amount: 30, clampToZero: true }],
      anchorBlockId: "runes-desc",
    },
    {
      id: "return-to-chapter",
      type: "choice",
      source: "chamber-of-runes",
      target: "dark-chapter",
      text: "Return to the Dark Chapter",
      anchorBlockId: "runes-desc",
    },
    {
      id: "heal-with-elixir",
      type: "choice",
      source: "collapsed-bridge",
      target: "collapsed-bridge",
      text: "Drink the healing elixir (+50 HP)",
      conditions: [{ type: "hasEntity", entityId: "elixir" }],
      effects: [
        { type: "addResource", key: "health", amount: 50 },
        { type: "revokeEntity", entityId: "elixir" },
      ],
      anchorBlockId: "bridge-desc",
    },
    {
      id: "cast-heal",
      type: "choice",
      source: "collapsed-bridge",
      target: "collapsed-bridge",
      text: "Cast Heal Spell (+40 HP, -20 MP, 3t CD)",
      conditions: [
        { type: "hasEntity", entityId: "heal-spell" },
        { type: "resourceAtLeast", key: "mana", value: 20 },
        { type: "resourceLessThan", key: "heal_cooldown", value: 1 },
      ],
      effects: [
        { type: "addResource", key: "health", amount: 40 },
        { type: "spendResource", key: "mana", amount: 20, clampToZero: true },
        { type: "addResource", key: "heal_cooldown", amount: 3 },
      ],
      anchorBlockId: "bridge-desc",
    },
    {
      id: "climb-rubble",
      type: "choice",
      source: "collapsed-bridge",
      target: "forgotten-crypt",
      text: "Climb through the rubble (-20 HP)",
      conditions: [{ type: "resourceAtLeast", key: "health", value: 30 }],
      effects: [{ type: "spendResource", key: "health", amount: 20, clampToZero: true }],
      anchorBlockId: "bridge-desc",
    },
    {
      id: "succumb-to-injuries",
      type: "choice",
      source: "collapsed-bridge",
      target: "death",
      text: "Succumb to your injuries",
      anchorBlockId: "bridge-desc",
    },
    {
      id: "unlock-casket",
      type: "choice",
      source: "forgotten-crypt",
      target: "victory",
      text: "Unlock the iron casket",
      conditions: [{ type: "hasEntity", entityId: "key" }],
      anchorBlockId: "crypt-desc",
    },
    {
      id: "lockpick-casket",
      type: "choice",
      source: "forgotten-crypt",
      target: "victory",
      text: "Lockpick the iron casket",
      conditions: [{ type: "hasEntity", entityId: "lockpick" }],
      anchorBlockId: "crypt-desc",
    },
    {
      id: "die-at-crypt",
      type: "choice",
      source: "forgotten-crypt",
      target: "death",
      text: "Succumb to your wounds in the crypt",
      anchorBlockId: "crypt-desc",
    },
  ],
})
